MONGODB_HOST: mongodb-{{ env }}.vigi-devops.fun  #mongodb-dev.vigi-devops.fun
REDIS_HOST: redis.vigi-devops.fun
CATALOGUE_HOST: catalogue.vigi-devops.fun
CART_HOST: cart.vigi-devops.fun
USER_HOST: user.vigi-devops.fun
RABBITMQ_HOST: rabbitmq.vigi-devops.fun
MYSQL_HOST: mysql.vigi-devops.fun
SHIPPING_HOST: shipping.vigi-devops.fun
PAYMENT_HOST: payment.vigi-devops.fun